#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$(realpath "$0")")/.." || exit

list_files() {
  git ls-files | while read -r line; do if [[ "$line" = *.sh ]] || file "$line" | grep -qw Bourne; then echo "$line"; fi; done
}

list_files | xargs shellcheck -e SC1090 -e SC2119 -e SC1091 -e SC2121 -e SC2094 -e SC2015
