name: Create a snapshot image
on:
  push:
  workflow_dispatch:
env:
  GH_TOKEN: ${{ github.token }}
jobs:
  demo_current:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create snapshot
        id: snapshot
        run: |
          if true # set to false when testing
          then
               path="snsdemo_snapshot_${{ matrix.os }}.tar.xz"
               time bin/dfx-sns-demo-install --verbose
               time bin/dfx-snapshot-mk-stock --snapshot "$path"
          else
               path="snsdemo_snapshot_${{ matrix.os }}.test"
               echo foo > "$path"
          fi
          echo "path=$path" >> "$GITHUB_OUTPUT"
      - name: Release if applicable
        run: |
          set -x
          artefacts=( "${{ steps.snapshot.outputs.path }}" )
          ls -l "${artefacts[@]}"
          : Creates or update releases for every tag pointing at this commit
          for tag in $(git tag --points-at HEAD) ; do
            : Creates or updates a release for the tag
            if gh release view "$tag"
            then gh release upload --clobber "$tag" "${artefacts[@]}" || true
            else gh release create --title "Release for tags/$tag" --draft --notes "Build artefacts from tag: $tag" "$tag" "${artefacts[@]}"
            fi
            : Optionally, make the release public
            [[ "$tag" != release-* ]] || {
                    echo "Making release public"
                    gh release edit "$tag" --draft=false
            }
          done
          : Updates 'tip' release, if this was triggered by a push to main or 'test-release'.
          : This can be exercised without a PR by pushing to 'test-release'.
          if [[ "${{github.event_name}}" == 'push' ]] && ( [[ "${{github.ref_name}}" == 'main' ]] || [[ "${{github.ref_name}}" == 'test-release' ]] ) ; then
            gh release upload --clobber tip "${artefacts[@]}" || true
          fi
